/**
 * Injects runtime web/PWA config so Supabase works even when
 * EXPO_PUBLIC_* vars were missing at Metro bundle time (e.g. Vercel build).
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, "..", "public", "hodix-env.js");

/** Production defaults — anon key is public (same as eas.json / Supabase publishable). */
const DEFAULTS = {
  EXPO_PUBLIC_SUPABASE_URL: "https://lrbhojxlofweotajnrhh.supabase.co",
  EXPO_PUBLIC_SUPABASE_ANON_KEY:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyYmhvanhsb2Z3ZW90YWpucmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3ODgzOTAsImV4cCI6MjA5NjM2NDM5MH0.b0ftbbS23W7_d0mdM5WYECvCQXzAazGdhZtbMGld7gA",
  EXPO_PUBLIC_SITE_URL: "https://www.hodix.app",
};

const KEYS = [
  "EXPO_PUBLIC_SUPABASE_URL",
  "EXPO_PUBLIC_SUPABASE_ANON_KEY",
  "EXPO_PUBLIC_SITE_URL",
  "EXPO_PUBLIC_SENTRY_DSN",
  "EXPO_PUBLIC_CINETPAY_API_KEY",
  "EXPO_PUBLIC_CINETPAY_SITE_ID",
  "EXPO_PUBLIC_PAYNOTE_MTN_ENABLED",
];

const config = {};
for (const key of KEYS) {
  const val = process.env[key]?.trim() || DEFAULTS[key] || "";
  if (val) config[key] = val;
}

const js = `/* Generated by scripts/inject-web-env.mjs — do not edit */
window.__HODIX_ENV__ = ${JSON.stringify(config, null, 0)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, js, "utf8");
console.log("[inject-web-env] wrote", outPath, Object.keys(config).join(", "));
